project:
  type: book
  output-dir: docs

book:
  title: "Building Blocks"
  author: "andrés castro araújo"
  date: last-modified
  chapters:
    - index.qmd
    - calculus.qmd
    - part: prob.qmd
      chapters: 
        - prob-intro.qmd
        - prob-counting.qmd
        - prob-random-vars.qmd
        - prob-sum-dist.qmd
        - prob-transformations.qmd
    - part: rn.qmd
      chapters:
        - rn-methods.qmd
        - rn-integration.qmd
        - rn-mcmc.qmd
    - part: cm.qmd
      chapters: 
        - cm-introduction.qmd
        - cm-nhst.qmd
        - cm-modeling.qmd
        - cm-visualizing.qmd
    - part: computing.qmd
      chapters:
        - computing-rcpp.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: lumen
    mainfont: Amiri
    monofont: Fira Code
    fontsize: 1em

execute:
  freeze: auto

